"""Build every number, table and figure in the 1 October 2026 fuzzy-skin report.

    python3 src/build_report.py            (repository; writes build/)
    python3 7_code/build_report.py         (unzipped data package; writes rebuilt/)

Nothing in report/report.tex is typed by hand: numbers come from
build/numbers.tex (LaTeX macros), tables from build/tables/*.tex, figures from
build/fig/*.pdf. The analysis-ready tables shipped with the report are written
to build/derived/.
"""
import json
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import analysis  # noqa: E402
import data as D  # noqa: E402
import keyence  # noqa: E402

TAB = D.BUILD / "tables"
DER = D.BUILD / "derived"
KEY = {s: v["key"] for s, v in D.SPECIMENS.items()}          # v1_Ra20 -> "A"
AKWA_CP = (0.05, 0.30)          # Savonius maximum averaged power coefficients, Akwa et al. 2012
WORDS = {0: "zero", 1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
         7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve"}


# ------------------------------------------------------------ formatting --
def neg(s):
    return s.replace("-", "\\ensuremath{-}")


def pct(x, nd=1, sign=True):
    """Percentage of a fraction x; two decimals if it would otherwise print as 0.0."""
    v = 100 * x
    if 0 < abs(v) < 0.05:
        nd = max(nd, 2)
    return neg(f"{v:+.{nd}f}" if sign else f"{v:.{nd}f}")


def pval(p):
    """'p' relation for LaTeX math mode: <0.001 below 0.001, otherwise =value."""
    if p < 1e-3:
        return "<0.001"
    return f"={p:.3f}" if p < 0.1 else f"={p:.2f}"


def ci(lo, hi, nd=1):
    return f"[{pct(lo, nd)},\\ {pct(hi, nd)}]"


def sig3(x):
    """Three significant figures, thin-space thousands separators."""
    if x >= 1000:
        return f"{int(float(f'{x:.3g}')):,}".replace(",", "\\,")
    return f"{x:.3g}"


def label(spec):
    return D.SPECIMENS[spec]["label"]


def write(path, text):
    Path(path).write_text(text, encoding="utf-8")


def check(cond, msg):
    if not cond:
        raise RuntimeError(msg)


def main():
    for d in (TAB, DER):
        d.mkdir(parents=True, exist_ok=True)
    stems, excluded = D.discover()
    runs = {k: D.load(k) for ks in stems.values() for k in ks}
    P = {k: D.peaks(runs[k]) for k in runs}
    T = {k: D.thevenin(runs[k]) for k in runs}

    # integrity: the recomputed arg max must equal the rig's logged value
    peak_diff = max(float((P[k].p_max_w - P[k].logged_p_max_w).abs().max()) for k in P)
    check(peak_diff < 1e-9, f"recomputed peak differs from the log by {peak_diff} W")
    sp = sorted(set.intersection(*[set(P[k].fan_rpm_cmd) for k in P]))
    check(all(len(P[k]) == len(sp) for k in P), "set points differ between runs")

    t0 = min(runs[k]["points"].t_unix.min() for k in runs)
    t_start_h = np.array([[(runs[k]["points"].t_unix.min() - t0) / 3600 for k in stems[s]] for s in D.ORDER])
    A = analysis.analyse(P, T, stems, sp, t_start_h)

    # rotor speed (T. Kang): same set points; every value a whole number of samples per revolution
    S = {k: D.rotor_speed(k) for k in runs}
    check(all(list(S[k].fan_rpm_cmd) == list(sp) for k in S), "rotor-speed set points differ from the runs")
    fs = D.tacho_fs()
    n_all = pd.concat(S.values()).rotor_rpm.values
    check((np.abs(60 * fs / np.round(60 * fs / n_all) - n_all) <= 0.5).all(),
          "a rotor speed is not 60*Fs/k for a whole number of samples k")
    A["spd"] = analysis.speed(S, P, stems, sp, T)
    A["t_start_h"] = t_start_h
    ke = A["spd"]["ke"]
    check(ke.std() / ke.mean() < 0.05, "first-step voltage / rotor speed varies by more than 5%: set points misaligned?")
    surf = keyence.by_rotor(D.SCANS)
    slicer = json.load(open(D.SLICER_JSON, encoding="utf-8"))
    cal = D.calibration()
    meas = cal[cal.source == "measured"]
    fits = {"measured": tuple(np.polyfit(meas.rpm, meas.velocity, 1))}

    M = macros(A, P, runs, stems, sp, surf, slicer, cal, meas, fits, fs)
    lines = ["% generated by build_report.py - do not edit"]
    for k, v in sorted(M.items()):
        check(k.isalpha(), f"macro name {k}")
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    write(D.BUILD / "numbers.tex", "\n".join(lines) + "\n")
    write(D.BUILD / "numbers.json", json.dumps(M, indent=1, sort_keys=True))
    tables(A, P, runs, stems, sp, surf, cal)
    derived(A, P, T, S, runs, stems, sp, surf, t_start_h)
    import figures
    figures.make_all(A, runs, stems, sp, cal, fits)
    print(f"built: {D.BUILD}  ({len(runs)} runs, {len(sp)} set points, {len(M)} macros;"
          f" excluded: {', '.join(excluded) or 'none'})")


# ---------------------------------------------------------------- macros --
def macros(A, P, runs, stems, sp, surf, slicer, cal, meas, fits, fs):
    M = {}
    v = D.wind(sp)
    allp = pd.concat(P.values())
    keys = [KEY[s] for s in D.ORDER]
    pl = stems[D.REF]

    # session, protocol and data quality
    M["nSP"], M["nRuns"], M["nSweeps"] = str(len(sp)), str(len(runs)), str(len(allp))
    M["nRunsWord"] = WORDS[len(runs)]
    M["spLo"], M["spHi"] = str(sp[0]), str(sp[-1])
    M["vLo"], M["vHi"] = f"{v[0]:.1f}", f"{v[-1]:.1f}"
    t = {k: D.times(runs[k]) for k in runs}
    M["tFirst"], M["tLast"] = min(a for a, _ in t.values()), max(b for _, b in t.values())
    mins = lambda hhmm: int(hhmm[:2]) * 60 + int(hhmm[3:])
    M["plainGap"] = str(mins(t[pl[1]][0]) - mins(t[pl[0]][0]))
    M["nClean"] = str(int(allp.clean.sum()))
    cuts = [(spec, j + 1, int(r.fan_rpm_cmd), r.last_frac) for spec in D.ORDER
            for j, k in enumerate(stems[spec]) for _, r in P[k][P[k].clean == 0].iterrows()]
    M["nCut"] = WORDS[len(cuts)]
    M["cutList"] = " and ".join(f"{label(s)} run~{j} at {c}~rpm ({100 * f:.0f}\\%)" for s, j, c, f in cuts) or "none"
    M["dwellLo"], M["dwellHi"] = str(int(allp.dwells.min())), str(int(allp.dwells.max()))
    M["nFallback"] = WORDS.get(int((allp.fit_points == 0).sum()), str(int((allp.fit_points == 0).sum())))
    M["thevRtwo"] = f"{A['thev_r2_min']:.3f}"
    M["fanRange"], M["fanTop"] = f"{A['fan_range_a']:.1f}", f"{A['fan_top_a']:.1f}"
    M["plainPair"] = pct(A["plain_pair"])
    top = {k: P[k].set_index("fan_rpm_cmd").p_max_w[sp[-1]] for k in pl}
    M["breakDiff"] = f"{100 * abs(top[pl[1]] / top[pl[0]] - 1):.1f}"
    M["reLo"] = f"{v[0] * D.CHORD_M / D.NU_STD / 1e4:.1f}"
    M["reHi"] = f"{v[-1] * D.CHORD_M / D.NU_STD / 1e5:.1f}"
    M["areaSw"], M["rhoStd"] = f"{D.AREA_M2:.4f}", f"{D.RHO_STD:.3f}"
    g = D._geo
    M["geoR"], M["geoH"] = f"{g['rotor']['radius_m']:.4f}", f"{g['rotor']['span_m']:.4f}"
    M["geoChord"], M["geoDepth"] = f"{g['blade_section']['chord_mm']:.0f}", f"{g['blade_section']['depth_mm']:.1f}"
    M["geoWall"], M["geoArc"] = f"{g['blade_section']['wall_mm']:.2f}", f"{g['blade_section']['arc_deg']:.0f}"
    meta = runs[pl[0]]["meta"]
    for k in runs:
        check(runs[k]["meta"]["protocol_detail"] == meta["protocol_detail"], "protocol_detail differs")
        check(runs[k]["meta"]["protocol_extra"] == meta["protocol_extra"], "protocol_extra differs")
    pd_ = dict(kv.split("=") for kv in meta["protocol_detail"].split(";"))
    px = dict(kv.split("=") for kv in meta["protocol_extra"].split(";"))
    M["stepmA"] = f"{1000 * float(pd_['step']):.0f}"
    M["stepMinmA"] = f"{1000 * float(px['min_step_amps']):.0f}"
    M["dwellS"] = f"{float(pd_['dwell']):.0f}"
    M["stopPct"] = f"{float(pd_['operate']):.0f}"
    M["vOff"] = f"{float(pd_['voff']):.1f}"                     # host's voltage floor (load's voltage-off setting)
    M["stopConfirm"] = WORDS[int(pd_["confirm"])]
    M["settleTolPct"] = f"{100 * float(px['settle_tol']):.0f}"
    M["settlePoll"] = f"{float(px['settle_poll']):.1f}"
    M["settleConfirm"] = WORDS[int(px["settle_confirm"])]
    M["settleMin"], M["settleMax"] = f"{float(px['settle_min']):.0f}", f"{float(px['settle_max']):.0f}"
    M["rpmTolAbs"], M["rpmTolPct"] = f"{float(px['rpm_tol_abs']):.0f}", f"{100 * float(px['rpm_tol_frac']):.0f}"
    M["runMin"] = f"{np.median([(runs[k]['points'].t_unix.max() - runs[k]['points'].t_unix.min()) / 60 for k in runs]):.0f}"
    M["nRise"] = WORDS[sum(D.first_dwell_rise(runs[k], sp[0]) for k in runs)]
    M["pLowMin"], M["pLowMax"] = f"{A['curve'][:, 0].min():.3f}", f"{A['curve'][:, 0].max():.3f}"

    # rotor comparison
    tk = A["tk"]
    M["sigRun"], M["dofRun"], M["qTukey"] = f"{100 * tk['sigma']:.2f}", str(tk["dof"]), f"{tk['q']:.2f}"
    M["hwTukey"], M["hwTukeyLog"] = f"{100 * math.expm1(tk['hw']):.1f}", f"{tk['hw']:.3f}"
    ow = A["oneway"]
    M["Frot"], M["pRot"] = f"{ow['F']:.0f}", pval(ow["p"])
    M["permP"], M["permN"] = f"1/{round(1 / A['perm']['p'])}", str(A["perm"]["n"] // math.factorial(len(D.ORDER)))
    check(abs(A["perm"]["p"] - 1 / round(1 / A["perm"]["p"])) < 1e-12, "permutation p is not 1/k")
    for a in range(4):
        for b in range(a + 1, 4):
            c, cf = tk["pairs"][(a, b)], A["tk_fit"]["pairs"][(a, b)]
            nm = keys[a] + keys[b]
            M[f"c{nm}"], M[f"c{nm}lo"], M[f"c{nm}hi"] = pct(c["level"]), pct(c["lo"]), pct(c["hi"])
            M[f"p{nm}"] = pval(c["p"])
            M[f"f{nm}"], M[f"f{nm}lo"], M[f"f{nm}hi"] = pct(cf["level"]), pct(cf["lo"]), pct(cf["hi"])
            M[f"pf{nm}"] = pval(cf["p"])
            if c["resolved"]:
                M[f"tau{nm}"] = f"{100 * A['tau'][(a, b)]:.1f}"
    M["sigFit"] = f"{100 * A['tk_fit']['sigma']:.2f}"
    M["fitMaxDiff"] = f"{max(abs(A['tk_fit']['pairs'][k]['level'] - tk['pairs'][k]['level']) for k in tk['pairs']) * 100:.1f}"
    M["nResolved"] = WORDS[sum(c["resolved"] for (a, b), c in tk["pairs"].items() if a < b)]
    M["nResolvedCap"] = M["nResolved"].capitalize()
    mp = max(abs(A["yrj"][r, 1] - A["yrj"][r, 0]) for r in range(len(D.ORDER)))
    M["maxPair"] = str(math.ceil(100 * math.expm1(mp)))      # ratio of a rotor's two run means
    dm = A["drift"]
    M["driftRate"], M["driftLo"], M["driftHi"] = pct(dm["beta"]), pct(dm["beta_lo"]), pct(dm["beta_hi"])
    M["driftDof"] = str(dm["dof"])
    for b in range(1, 4):
        c = dm["change"][b]
        M[f"cd{keys[b]}"], M[f"cd{keys[b]}lo"], M[f"cd{keys[b]}hi"] = pct(c["level"]), pct(c["lo"]), pct(c["hi"])

    # dependence on wind speed
    for tag, an in (("", A["anova"]), ("Tex", A["anova_tex"]), ("Trim", A["anova_trim"]),
                    ("Rint", A["anova_rint"])):
        r = an["RS"]
        M[f"Fint{tag}"] = f"{r['F']:.1f}"
        M[f"dfInt{tag}A"], M[f"dfInt{tag}B"] = str(r["df"]), str(r["df_den"])
        M[f"pInt{tag}"] = pval(r["p"])
    an = A["anova"]
    M["Frun"], M["pRun"] = f"{an['J']['F']:.2f}", pval(an["J"]["p"])
    M["dfRunA"], M["dfRunB"] = str(an["J"]["df"]), str(an["J"]["df_den"])
    M["sigE"] = f"{100 * an['sigma_e']:.1f}"
    sd = an["sd_by_setpoint"]
    M["sigEmax"], M["sigEmaxRpm"] = f"{100 * sd.max():.1f}", str(sp[int(np.argmax(sd))])
    M["sigEmin"], M["sigEminRpm"] = f"{100 * sd.min():.1f}", str(sp[int(np.argmin(sd))])
    M["trimDropped"] = " and ".join(str(s) for s in A["trim_dropped"])
    for r in (2, 3):
        g = A["gain"][r]
        M[f"gMax{keys[r]}"], M[f"gMaxV{keys[r]}"] = pct(g.max()), f"{v[int(np.argmax(g))]:.0f}"
    # where the gains are largest: the wind speeds at which FS 0.20 exceeds bandThr
    thr = 0.25
    big = np.where(A["gain"][3] > thr)[0]
    check(len(big) > 0 and (np.diff(big) == 1).all(), "FS 0.20's large gains are not one contiguous band")
    M["bandThr"] = f"{100 * thr:.0f}"
    M["bandLo"], M["bandHi"] = f"{v[big].min():.0f}", f"{v[big].max():.0f}"
    M["reBandLo"] = f"{v[big].min() * D.CHORD_M / D.NU_STD / 1e4:.1f}"      # chord Reynolds number, x 1e4
    M["reBandHi"] = f"{v[big].max() * D.CHORD_M / D.NU_STD / 1e4:.1f}"
    sv, sl = A["step_v"], A["step_slope"]
    rng = lambda a, nd=0: (f"{a.min():.{nd}f}" if f"{a.min():.{nd}f}" == f"{a.max():.{nd}f}"
                           else f"{a.min():.{nd}f}--{a.max():.{nd}f}")
    for r, k in enumerate(keys):
        M[f"stepV{k}"] = rng(sv[r])                              # midpoint(s) of the two runs
        M[f"stepSlope{k}"] = rng(sl[r], 1)
    M["spDv"] = f"{100 * D.CAL_A:.1f}"                           # set-point spacing in m/s
    for r in (2, 3):                                             # FS 0.10 and FS 0.20 below both Plain runs
        check(sv[r].max() < sv[0].min(), f"{keys[r]}'s steepest segment is not below both Plain runs")
    check(sv[1].min() < sv[0].max() and sv[1].max() >= sv[0].min(), "FS 0.05 no longer overlaps Plain")

    # power and electrical power coefficient
    for r, k in enumerate(keys):
        M[f"pTop{k}"] = f"{A['curve'][r][-1]:.2f}"
        M[f"cpTop{k}"] = f"{100 * A['cp'][r][-1]:.2f}"
    M["cpLo"], M["cpHi"] = f"{100 * A['cp'].min():.2f}", f"{100 * A['cp'].max():.2f}"
    # Akwa, Vielmo and Petry (2012): maximum averaged C_P of Savonius rotors about 0.05-0.30
    M["akwaLo"], M["akwaHi"] = (f"{c / A['cp'].max():.0f}" for c in AKWA_CP)

    # Thevenin source
    for key in ("voc", "rint"):
        t_ = A["tk_" + key]
        M[f"sig{key.capitalize()}"] = f"{100 * t_['sigma']:.2f}"
        for b in range(1, 4):
            c = t_["pairs"][(0, b)]
            M[f"{key}{keys[b]}"], M[f"{key}{keys[b]}lo"], M[f"{key}{keys[b]}hi"] = \
                pct(c["level"]), pct(c["lo"]), pct(c["hi"])
    for b in range(1, 4):
        M[f"vocSq{keys[b]}"] = pct((1 + A["tk_voc"]["pairs"][(0, b)]["level"]) ** 2 - 1)
    rg = A["rint_gain"][3]
    M["rintMinC"], M["rintMinVC"] = pct(rg.min()), f"{v[int(np.argmin(rg))]:.0f}"
    M["rintMaxC"], M["rintMaxVC"] = pct(rg.max()), f"{v[int(np.argmax(rg))]:.0f}"
    neg_, pos_ = np.where(rg < 0)[0], np.where(rg > 0)[0]
    lowband = neg_[(v[neg_] > 13) & (v[neg_] < 26)]              # the run of negatives below 26 m/s
    check((np.diff(lowband) == 1).all(), "FS 0.20 R_int is not below Plain over one contiguous band")
    M["rintNegLo"], M["rintNegHi"] = f"{v[lowband].min():.0f}", f"{v[lowband].max():.0f}"
    hi = pos_[v[pos_] > v[lowband].max()]
    check(len(hi) == len(v) - lowband.max() - 1, "FS 0.20 R_int is not above Plain at every speed beyond the band")
    M["rintPosLo"] = f"{v[hi].min():.0f}"
    # how many of these wind speeds the other textured rotors share FS 0.20's sign
    span = np.concatenate([lowband, hi])
    M["rintSignN"] = str(len(span))
    for r in (1, 2):
        M[f"rintSign{keys[r]}"] = str(int((np.sign(A["rint_gain"][r, span]) == np.sign(rg[span])).sum()))
    # share of the ln-power gain carried by R_int (P ~ Voc^2/4R) where the gains are largest
    share = []
    for r in (2, 3):
        for i in big:
            g = 2 * math.log1p(A["voc_gain"][r, i]) - math.log1p(A["rint_gain"][r, i])
            if g > 0:
                share.append(-math.log1p(A["rint_gain"][r, i]) / g)
    M["rintShareMax"] = f"{100 * max(share):.0f}"
    M["rintPlainLo"] = f"{A['rint_curve'][0][0]:.0f}"
    M["rintPlainHi"] = f"{A['rint_curve'][0][-1]:.0f}"
    M["rintPlainDiff"] = f"{A['rint_curve'][0][0] - A['rint_curve'][0][-1]:.0f}"
    M["matchLo"], M["matchHi"] = f"{A['match_lo']:.2f}", f"{A['match_hi']:.2f}"

    # rotor speed: T. Kang's light-load speed n0 at 600-1800 rpm, compared as P_max is
    sa, st = A["spd"], A["spd"]["tk"]
    vs = D.wind(sa["sp"])
    M["spdSpLo"], M["vSpdLo"] = str(sa["sp"][0]), f"{vs[0]:.1f}"
    M["sigSpd"] = f"{100 * st['sigma']:.2f}"
    for a in range(4):
        for b in range(a + 1, 4):
            c, nm = st["pairs"][(a, b)], keys[a] + keys[b]
            M[f"spd{nm}"], M[f"spd{nm}lo"], M[f"spd{nm}hi"] = pct(c["level"]), pct(c["lo"]), pct(c["hi"])
            M[f"pspd{nm}"] = pval(c["p"])
    resolved = {k: c["resolved"] for k, c in st["pairs"].items() if k[0] < k[1]}
    M["nSpdResolved"] = WORDS[sum(resolved.values())]
    check(all(resolved.values()), "speed: a pair is no longer resolved (the text says all six are)")
    check(st["pairs"][(0, 1)]["lo"] < 0.005, "speed: FS 0.05 vs Plain is no longer at the limit of resolution")
    # V1 is continuous: it must make the same calls as the quantised n0
    tv = sa["tk_v1"]
    check(all(tv["pairs"][k]["resolved"] == r for k, r in resolved.items()), "V1 and n0 make different calls")
    for b in range(1, 4):
        c = tv["pairs"][(0, b)]
        M[f"vfirst{keys[b]}"], M[f"vfirst{keys[b]}lo"], M[f"vfirst{keys[b]}hi"] = pct(c["level"]), pct(c["lo"]), pct(c["hi"])
    M["nSameQ"], M["nPairsQ"] = str(sa["n_same"]), str(sa["n_pairs"])
    M["nSpdPoints"] = str(sa["n"].size)                         # rotor x run x set point, 600-1800 rpm
    M["FrotSpd"], M["pRotSpd"] = f"{sa['oneway']['F']:.0f}", pval(sa["oneway"]["p"])
    check(abs(sa["perm"]["p"] - A["perm"]["p"]) < 1e-12, "speed permutation p differs from power's")
    r_ = sa["anova"]["RS"]
    M["FintSpd"], M["pIntSpd"] = f"{r_['F']:.1f}", pval(r_["p"])
    M["dfIntSpdA"], M["dfIntSpdB"] = str(r_["df"]), str(r_["df_den"])
    cv_, lc = sa["curve"], sa["lam_curve"]                       # rotor geometric means [r, s]
    M["spdLowMin"], M["spdLowMax"] = f"{cv_[:, 0].min():.0f}", f"{cv_[:, 0].max():.0f}"
    M["spdTopMin"], M["spdTopMax"] = f"{cv_[:, -1].min():.0f}", f"{cv_[:, -1].max():.0f}"
    M["lamLowMin"], M["lamLowMax"] = f"{lc[:, 0].min():.2f}", f"{lc[:, 0].max():.2f}"
    M["lamTopMin"], M["lamTopMax"] = f"{lc[:, -1].min():.2f}", f"{lc[:, -1].max():.2f}"
    M["lamMaxAll"] = f"{sa['lam'].max():.2f}"                    # any run, any light-load set point
    rise = 100 * (lc[:, -1] / lc[:, 0] - 1)
    M["lamRiseLo"], M["lamRiseHi"] = f"{rise.min():.0f}", f"{rise.max():.0f}"
    M["tachoFs"] = f"{fs:.2f}"
    # resolution: n0 is rounded to 1 rpm and is 60*fs/k for whole k, so its step is the
    # larger of 1 rpm and n0^2/(60 fs)
    n_all = sa["n_all"]
    res = lambda n: 100 * np.maximum(1 / n, n / (60 * fs))
    M["resLo"], M["resHi"] = f"{res(n_all.min()):.1f}", f"{res(n_all.max()):.1f}"
    M["resMin"] = f"{res(n_all).min():.1f}"
    M["resCross"] = f"{math.sqrt(60 * fs):.0f}"
    M["spdMin"], M["spdMax"] = f"{n_all.min():.0f}", f"{n_all.max():.0f}"
    M["loadArmmA"] = f"{1000 * float(pd_['step']) * 0.5:.0f}"
    gap = 100 * sa["first_gap"]
    M["gapLo"], M["gapHi"] = f"{gap.min():.0f}", f"{gap.max():.0f}"
    check((gap > 0).all(), "n0 at the first set point is not below the speed V1 implies")
    ke = 1000 * sa["ke"]                                         # mV per rpm, [r, j, s]
    M["keMean"], M["keCV"] = f"{ke.mean():.1f}", f"{100 * ke.std() / ke.mean():.1f}"
    kr = ke.mean(axis=(1, 2))
    M["keRotSpread"] = f"{100 * (kr.max() - kr.min()) / ke.mean():.2f}"
    M["keSlope"], M["keIcept"] = f"{1000 * sa['fit']['slope']:.1f}", f"{-sa['fit']['icept']:.2f}"
    tke = sa["tk_ke"]["pairs"]
    check(not any(c["resolved"] for k, c in tke.items()), "V1/n0 differs between rotors")
    kmax = max((k for k in tke if k[0] < k[1]), key=lambda k: abs(tke[k]["level"]))
    M["keDiff"], M["keDifflo"], M["keDiffhi"] = pct(tke[kmax]["level"]), pct(tke[kmax]["lo"]), pct(tke[kmax]["hi"])
    M["keDiffPair"] = f"{label(D.ORDER[kmax[1]])} vs {label(D.ORDER[kmax[0]])}"
    M["keBound"] = f"{100 * max(max(abs(c['lo']), abs(c['hi'])) for c in tke.values()):.1f}"   # any pair, either limit
    check(sa["fit"]["icept"] < 0, "V1 = a + b n0 no longer has a negative intercept (rectifier drop)")
    first = allp[allp.fan_rpm_cmd > sp[0]]
    M["iFirstLo"], M["iFirstHi"] = f"{1000 * first.i_first_a.min():.0f}", f"{1000 * first.i_first_a.max():.0f}"
    diff = []                                                    # n0 vs V1 and vs V_oc, same set points
    for b in range(1, 4):
        lv = st["pairs"][(0, b)]["level"]
        diff += [abs(lv - tv["pairs"][(0, b)]["level"]), abs(lv - sa["tk_voc"]["pairs"][(0, b)]["level"])]
        c = sa["tk_voc"]["pairs"][(0, b)]
        M[f"vocs{keys[b]}"] = pct(c["level"])
    M["spdVoltDiff"] = f"{100 * max(diff):.1f}"                 # percentage points
    tvn = sa["tk_vocn"]["pairs"]
    check(not any(c["resolved"] for c in tvn.values()), "V_oc/n0 differs between rotors")
    kv = max((k for k in tvn if k[0] < k[1]), key=lambda k: abs(tvn[k]["level"]))
    M["vocnDiff"], M["vocnDifflo"], M["vocnDiffhi"] = pct(tvn[kv]["level"]), pct(tvn[kv]["lo"]), pct(tvn[kv]["hi"])
    M["vocnDiffPair"] = f"{label(D.ORDER[kv[1]])} vs {label(D.ORDER[kv[0]])}"
    gb = sa["voc_below_v1"]
    mean_gap = gb.mean(axis=(0, 1))
    first = next(i for i in range(len(mean_gap)) if (mean_gap[i:] > 0).all())
    M["vocBelowFrom"] = str(sa["sp"][first])
    M["vocBelowMax"] = f"{100 * gb[:, :, first:].max():.1f}"                  # any single run
    M["vocBelowMeanLo"], M["vocBelowMeanHi"] = f"{100 * mean_gap[first:].min():.1f}", f"{100 * mean_gap[first:].max():.1f}"
    below = vs < v[big].min()                                    # below the power band
    for r in (2, 3):
        g = 100 * sa["gain"][r]
        check((g > 0).all(), f"{keys[r]}: a speed gain is not positive")
        M[f"spdBelow{keys[r]}"], M[f"spdFrom{keys[r]}"] = rng(g[below]), rng(g[~below])
    M["spdSplitLo"], M["spdSplitHi"] = f"{vs[below].max():.1f}", f"{vs[~below].min():.1f}"
    # the drift slope rests on the pair of runs farthest apart in time (Plain)
    t_ = A["t_start_h"]
    lev = (t_[:, 1] - t_[:, 0]) ** 2
    M["driftShare"] = f"{100 * lev[0] / lev.sum():.0f}"
    check(lev.argmax() == 0, "the drift slope no longer rests mainly on the Plain pair")

    # surface
    for spec, s in surf.items():
        k = KEY[spec]
        M[f"Pa{k}"], M[f"Ra{k}"] = f"{s['Pa']:.1f}", f"{s['Ra']:.1f}"
        if spec != "v1_Ra80":                                    # FS 0.20 has no layer period
            M[f"pitch{k}"] = f"{s['pitch_um'] / 1000:.2f}"
        if s["Pa_spread"] is not None:
            M[f"PaSpread{k}"] = f"{s['Pa_spread']:.1f}"
            M[f"PaSpreadPct{k}"] = f"{100 * s['Pa_spread'] / s['Pa']:.0f}"
            M[f"RaSpread{k}"] = f"{s['Ra_spread']:.1f}"
    scans = [sc for s in surf.values() for sc in s["scans"]]
    M["fieldX"] = f"{np.mean([sc['field_um'][0] for sc in scans]) / 1000:.1f}"
    M["fieldY"] = f"{np.mean([sc['field_um'][1] for sc in scans]) / 1000:.1f}"
    M["pixel"] = f"{scans[0]['dx_um']:.2f}"
    M["evalLo"] = f"{min(sc['eval_um'] for sc in scans) / 1000:.2f}"
    M["evalHi"] = f"{max(sc['eval_um'] for sc in scans) / 1000:.2f}"
    # ISO 16610-21 transmission of the roughness profile at the measured layer periods
    alpha, lc = math.sqrt(math.log(2) / math.pi), 250.0
    trans = lambda lam: 1 - math.exp(-math.pi * (alpha * lc / lam) ** 2)
    M["transP"] = f"{100 * trans(surf['v1_smooth']['pitch_um']):.0f}"
    M["transA"] = f"{100 * trans(surf['v1_Ra20']['pitch_um']):.0f}"
    M["PaRatioCB"] = f"{surf['v1_Ra80']['Pa'] / surf['v1_Ra40']['Pa']:.1f}"
    M["PaRatioBA"] = f"{surf['v1_Ra40']['Pa'] / surf['v1_Ra20']['Pa']:.2f}"
    # FS 0.05 vs FS 0.10: their Pa and Ra differ by less than the two FS 0.20 fields differ from each other
    a, b, c = surf["v1_Ra20"], surf["v1_Ra40"], surf["v1_Ra80"]
    for q in ("Pa", "Ra"):
        M[f"{q}DiffAB"] = f"{abs(a[q] - b[q]):.1f}"
        check(abs(a[q] - b[q]) < c[f"{q}_spread"], f"FS 0.05 and FS 0.10 {q} differ by more than the FS 0.20 field spread")
    rej = {spec: 1 - sum(sc["n_profiles"] for sc in s["scans"]) / sum(sc["n_columns"] for sc in s["scans"])
           for spec, s in surf.items()}
    M["rejLo"] = f"{100 * max(v_ for s_, v_ in rej.items() if s_ != 'v1_Ra80'):.1f}"
    M["rejC"] = f"{100 * rej['v1_Ra80']:.1f}"
    z, _ = keyence.display_map(D.SCANS / "801_Height.csv", clip_um=float("inf"))
    M["clipShareC"] = f"{100 * np.nanmean(np.abs(z) > 60):.0f}"      # FS 0.20 field shown in Fig. 1
    dates = sorted(sc["date"] for sc in scans)
    M["scanFirst"], M["scanLast"] = dates[0][11:16], dates[-1][11:16]

    # slicer project
    import datetime as dt
    d = dt.date.fromisoformat(slicer["saved"])
    M["slSaved"] = f"{d.day} {d:%B}"
    M["slPrinter"] = slicer["printer_profile"].replace(f" {slicer['nozzle_mm']:g} nozzle", "")
    M["slNozzle"], M["slLayer"] = f"{slicer['nozzle_mm']:.1f}", f"{slicer['layer_height_mm']:.2f}"
    M["slMaterial"], M["slPoint"] = slicer["material"], f"{slicer['fuzzy_point_distance_mm']:.1f}"
    M["slPaint"] = f"{100 * min(p['painted_area_fraction'] for p in slicer['plates']):.1f}"
    M["slSize"] = " \\times ".join(f"{x:.1f}" for x in sorted(slicer["plates"][0]["size_mm"]))
    M["slPlates"] = WORDS[slicer["plates_total"]]
    M["slWalls"] = WORDS[slicer["wall_loops"]]

    # wind-speed calibration
    M["calA"], M["calB"] = f"{D.CAL_A:.5f}", f"{-D.CAL_B:.3f}"
    M["calN"], M["calNmeas"], M["calNtrend"] = WORDS[len(cal)], WORDS[len(meas)], WORDS[len(cal) - len(meas)]
    M["calMeasRpm"], M["calMeasV"] = str(int(meas.rpm.max())), f"{meas.velocity.max():.1f}"
    tr = cal[cal.source != "measured"]
    M["calTrendLo"], M["calTrendHi"] = str(int(tr.rpm.min())), str(int(tr.rpm.max()))
    above = [s for s in sp if s > meas.rpm.max()]
    M["nSPabove"] = WORDS[len(above)]
    M["vAboveLo"] = f"{float(D.wind(above[0])):.1f}"
    inside = meas[meas.rpm.isin(sp)]
    off = D.wind(inside.rpm.values) / inside.velocity.values - 1
    M["calLowLo"], M["calLowHi"] = f"{100 * off.min():.1f}", f"{100 * off.max():.1f}"
    M["calLowVLo"], M["calLowVHi"] = f"{inside.velocity.min():.0f}", f"{inside.velocity.max():.0f}"
    a, b = fits["measured"]
    M["calMeasTop"] = f"{a * sp[-1] + b:.1f}"
    M["calDiffTop"] = f"{100 * (1 - (a * sp[-1] + b) / D.wind(sp[-1])):.0f}"
    M["calCpUnc"] = f"{100 * ((D.wind(sp[-1]) / (a * sp[-1] + b)) ** 3 - 1):.0f}"
    M["calMeasSd"] = f"{(meas.velocity - (a * meas.rpm + b)).std(ddof=2):.2f}"
    return M


# ---------------------------------------------------------------- tables --
def tables(A, P, runs, stems, sp, surf, cal):
    tk = A["tk"]
    v = D.wind(sp)

    lines = []
    for r, spec in enumerate(D.ORDER):
        s, su = D.SPECIMENS[spec], surf[spec]
        thick = "none" if s["fuzz_mm"] == 0 else f"{s['fuzz_mm']:.3f}"
        if r == 0:
            chg = "reference"
        else:
            c = tk["pairs"][(0, r)]
            chg = f"${pct(c['level'])}$ ${ci(c['lo'], c['hi'])}$"
        lines.append(" & ".join([s["label"], thick, f"{su['Pa']:.1f}", f"{su['Ra']:.1f}", chg,
                                 f"{A['curve'][r][-1]:.2f}"]) + r" \\")
    write(TAB / "headline.tex", "\n".join(lines) + "\n")

    lines = []
    for a in range(4):
        for b in range(a + 1, 4):
            c, cf = tk["pairs"][(a, b)], A["tk_fit"]["pairs"][(a, b)]
            lines.append(" & ".join([
                f"{label(D.ORDER[b])} vs {label(D.ORDER[a])}",
                f"${pct(c['level'])}$", f"${ci(c['lo'], c['hi'])}$", f"$p{pval(c['p'])}$",
                f"${pct(cf['level'])}$ ${ci(cf['lo'], cf['hi'])}$"]) + r" \\")
    write(TAB / "pairs.tex", "\n".join(lines) + "\n")

    an = A["anova"]
    names = dict(R="Rotor", S="Set point (wind speed)", RS="Rotor $\\times$ set point",
                 J="Run within rotor", E="Residual")
    against = dict(R="run within rotor", S="", RS="residual", J="residual", E="")
    lines = []
    for k in ("R", "S", "RS", "J", "E"):
        r = an[k]
        show = "F" in r and k != "S"                             # nobody doubts the set-point effect
        lines.append(" & ".join([names[k], str(r["df"]), sig3(1e4 * r["ms"]),
                                 sig3(r["F"]) if show else "", f"$p{pval(r['p'])}$" if show else "",
                                 against[k]]) + r" \\")
    write(TAB / "anova.tex", "\n".join(lines) + "\n")

    lines = []
    for r, spec in enumerate(D.ORDER):
        if r == 0:
            cells = [label(spec)] + ["reference"] * 3
        else:
            cells = [label(spec)]
            for c in (A["tk_voc"]["pairs"][(0, r)], A["tk_rint"]["pairs"][(0, r)], A["spd"]["tk"]["pairs"][(0, r)]):
                cells.append(f"${pct(c['level'])}$ ${ci(c['lo'], c['hi'])}$")
        cells += [f"{100 * A['cp'][r][-1]:.2f}", f"{A['spd']['lam_curve'][r][-1]:.2f}"]
        lines.append(" & ".join(cells) + r" \\")
    write(TAB / "rotor.tex", "\n".join(lines) + "\n")

    lines = []
    for r, spec in enumerate(D.ORDER):
        for j, k in enumerate(stems[spec]):
            a, b = D.times(runs[k])
            lines.append(" & ".join([label(spec) if j == 0 else "", str(j + 1), f"{a}–{b}",
                                     f"${pct(math.expm1(A['yrj'][r, j]))}$",
                                     "\\texttt{" + k.replace("_", "\\_") + "}"]) + r" \\")
    write(TAB / "session.tex", "\n".join(lines) + "\n")

    head = ("Fan & $v$ & " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{label(s)}}}" for s in D.ORDER)
            + r" \\" + "\n"
            + "".join(f"\\cmidrule(lr){{{3 + 2 * i}-{4 + 2 * i}}}" for i in range(4)) + "\n"
            + "rpm & m/s & " + " & ".join("1 & 2" for _ in D.ORDER) + r" \\" + "\n")
    pk = lambda r, j, i: P[stems[D.ORDER[r]][j]].set_index("fan_rpm_cmd").p_max_w[sp[i]]
    for name, value in (("data", lambda r, j, i: f"{pk(r, j, i):.4f}"),
                        ("speed", lambda r, j, i: (f"({A['spd']['n_all'][r, j, i]:.0f})" if i == 0
                                                   else f"{A['spd']['n_all'][r, j, i]:.0f}"))):
        body = []
        for i, (s_, vv) in enumerate(zip(sp, v)):
            cells = [str(s_), f"{vv:.1f}"] + [value(r, j, i) for r in range(len(D.ORDER)) for j in range(2)]
            body.append(" & ".join(cells) + r" \\")
        write(TAB / f"{name}.tex", "\\begin{tabular}{@{}rr" + " rr" * 4 + "@{}}\n\\toprule\n" + head
              + "\\midrule\n" + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n")

    lines = []
    for _, r in cal.iterrows():
        fit = float(D.wind(r.rpm))
        lines.append(" & ".join([str(int(r.rpm)), f"{r.velocity:.2f}",
                                 "measured" if r.source == "measured" else "trend line?",
                                 neg(f"{fit:.2f}"), neg(f"{fit - r.velocity:+.2f}")]) + r" \\")
    write(TAB / "calibration.tex", "\n".join(lines) + "\n")


# --------------------------------------------------------------- derived --
def derived(A, P, T, S, runs, stems, sp, surf, t_start_h):
    v = D.wind(sp)
    sa = A["spd"]

    def tagged(frames, k, spec, j):
        f = frames[k].copy()
        f.insert(0, "run", j + 1)
        f.insert(0, "run_name", k)
        f.insert(0, "fuzzy_skin_mm", D.SPECIMENS[spec]["fuzz_mm"])
        f.insert(0, "rotor", label(spec))
        return f

    pk = pd.concat([tagged(P, k, s, j) for s in D.ORDER for j, k in enumerate(stems[s])])
    pk = pk.drop(columns=["logged_p_max_w", "logged_p_fit_w", "last_frac", "fan_rpm_logged"])
    pk.to_csv(DER / "peak_power_by_run.csv", index=False, float_format="%.6g")
    th = pd.concat([tagged(T, k, s, j) for s in D.ORDER for j, k in enumerate(stems[s])])
    th.to_csv(DER / "thevenin_by_run.csv", index=False, float_format="%.6g")
    rs = []
    for r, spec in enumerate(D.ORDER):
        for j, k in enumerate(stems[spec]):
            f = tagged(S, k, spec, j)
            f.insert(f.columns.get_loc("fan_rpm_cmd") + 1, "wind_mps", D.wind(f.fan_rpm_cmd.values))
            f["light_load"] = (f.fan_rpm_cmd > sp[0]).astype(int)   # first set point settles under load
            f["tip_speed_ratio"] = sa["lam_all"][r, j]
            p1 = P[k].set_index("fan_rpm_cmd").reindex(sp)
            f["v_first_v"], f["i_first_a"] = p1.v_first_v.values, p1.i_first_a.values
            f["v_first_per_rpm_mv"] = 1000 * sa["v1_all"][r, j] / sa["n_all"][r, j]
            rs.append(f)
    pd.concat(rs).to_csv(DER / "rotor_speed_by_run.csv", index=False, float_format="%.6g")

    rows = []
    for r, spec in enumerate(D.ORDER):
        for j, k in enumerate(stems[spec]):
            a, b = D.times(runs[k])
            rows.append(dict(rotor=label(spec), fuzzy_skin_mm=D.SPECIMENS[spec]["fuzz_mm"], run=j + 1,
                             run_name=k, first_dwell=a, last_dwell=b, start_h=t_start_h[r, j],
                             p_max_change_vs_plain_pct=100 * math.expm1(A["yrj"][r, j]),
                             v_oc_change_vs_plain_pct=100 * math.expm1(A["voc_rj"][r, j]),
                             r_int_change_vs_plain_pct=100 * math.expm1(A["rint_rj"][r, j]),
                             rotor_rpm_change_vs_plain_pct=100 * math.expm1(sa["yrj"][r, j]),
                             steepest_rise_mps=A["step_v"][r, j]))
    pd.DataFrame(rows).to_csv(DER / "run_summary.csv", index=False, float_format="%.5g")

    rows = []
    for (a, b), c in A["tk"]["pairs"].items():
        if a < b:
            cf, cs = A["tk_fit"]["pairs"][(a, b)], sa["tk"]["pairs"][(a, b)]
            cv, cr = A["tk_voc"]["pairs"][(a, b)], A["tk_rint"]["pairs"][(a, b)]
            rows.append(dict(rotor=label(D.ORDER[b]), relative_to=label(D.ORDER[a]),
                             change_pct=100 * c["level"], tukey95_lo_pct=100 * c["lo"],
                             tukey95_hi_pct=100 * c["hi"], p_tukey=c["p"],
                             fit_change_pct=100 * cf["level"], fit_tukey95_lo_pct=100 * cf["lo"],
                             fit_tukey95_hi_pct=100 * cf["hi"], p_tukey_fit=cf["p"],
                             tipping_point_mounting_sd_pct=100 * A["tau"][(a, b)] if c["resolved"] else np.nan,
                             v_oc_change_pct=100 * cv["level"], v_oc_tukey95_lo_pct=100 * cv["lo"],
                             v_oc_tukey95_hi_pct=100 * cv["hi"],
                             r_int_change_pct=100 * cr["level"], r_int_tukey95_lo_pct=100 * cr["lo"],
                             r_int_tukey95_hi_pct=100 * cr["hi"],
                             rotor_rpm_change_pct=100 * cs["level"], rotor_rpm_tukey95_lo_pct=100 * cs["lo"],
                             rotor_rpm_tukey95_hi_pct=100 * cs["hi"], p_tukey_rotor_rpm=cs["p"]))
    pd.DataFrame(rows).to_csv(DER / "comparisons.csv", index=False, float_format="%.5g")

    dm = A["drift"]
    rows = [dict(term="drift per hour", estimate_pct=100 * dm["beta"], ci95_lo_pct=100 * dm["beta_lo"],
                 ci95_hi_pct=100 * dm["beta_hi"], dof=dm["dof"])]
    for b, c in dm["change"].items():
        rows.append(dict(term=f"{label(D.ORDER[b])} vs Plain, drift-adjusted", estimate_pct=100 * c["level"],
                         ci95_lo_pct=100 * c["lo"], ci95_hi_pct=100 * c["hi"], dof=dm["dof"]))
    pd.DataFrame(rows).to_csv(DER / "drift_model.csv", index=False, float_format="%.5g")

    rows = []
    trim = f"without {' and '.join(map(str, A['trim_dropped']))} rpm"
    src = dict(R="rotor", S="set point", RS="rotor x set point", J="run within rotor", E="residual")
    for name, an in (("ln P_max, all rotors", A["anova"]), ("ln P_max, textured rotors only", A["anova_tex"]),
                     (f"ln P_max, {trim}", A["anova_trim"]), ("ln R_int, all rotors", A["anova_rint"]),
                     ("ln V_oc, all rotors", A["anova_voc"]),
                     (f"ln n_0 (light-load rotor speed), all rotors, {sa['sp'][0]}-{sa['sp'][-1]} rpm",
                      sa["anova"])):
        for k in ("R", "S", "RS", "J", "E"):
            r = an[k]
            rows.append(dict(analysis=name, source=src[k], df=r["df"], ss=r["ss"], ms=r["ms"],
                             F=r.get("F"), df_den=r.get("df_den"), p=r.get("p")))
    pd.DataFrame(rows).to_csv(DER / "anova.csv", index=False, float_format="%.6g")

    rows = []
    for r, spec in enumerate(D.ORDER):
        for i, s_ in enumerate(sp):
            row = dict(rotor=label(spec), fan_rpm_cmd=s_, wind_mps=float(v[i]),
                       p_max_geomean_w=A["curve"][r, i], cp_el=A["cp"][r, i],
                       v_oc_geomean_v=A["voc_curve"][r, i], r_int_geomean_ohm=A["rint_curve"][r, i],
                       rotor_rpm_geomean=sa["curve"][r, i - 1] if i else np.nan,
                       tip_speed_ratio=sa["lam_curve"][r, i - 1] if i else np.nan)
            if r:
                row.update(p_max_change_vs_plain_pct=100 * A["gain"][r, i],
                           run1_change_pct=100 * A["gain_run"][r, 0, i],
                           run2_change_pct=100 * A["gain_run"][r, 1, i],
                           pointwise95_halfwidth_pct=100 * math.expm1(A["band_hw"][i]),
                           v_oc_change_vs_plain_pct=100 * A["voc_gain"][r, i],
                           r_int_change_vs_plain_pct=100 * A["rint_gain"][r, i],
                           rotor_rpm_change_vs_plain_pct=100 * sa["gain"][r, i - 1] if i else np.nan)
            rows.append(row)
    pd.DataFrame(rows).to_csv(DER / "rotor_by_wind_speed.csv", index=False, float_format="%.6g")

    pd.DataFrame([dict(rotor=label(spec), fuzzy_skin_mm=D.SPECIMENS[spec]["fuzz_mm"], scans=s["n_scans"],
                       columns=sum(sc["n_columns"] for sc in s["scans"]), profiles=s["n_profiles"],
                       Pa_um=s["Pa"], Ra_lc025_um=s["Ra"],
                       layer_period_um=np.nan if spec == "v1_Ra80" else s["pitch_um"],
                       Pa_scan_spread_um=s["Pa_spread"], Ra_scan_spread_um=s["Ra_spread"])
                  for spec, s in surf.items()]).to_csv(DER / "surface_roughness.csv", index=False, float_format="%.4g")


if __name__ == "__main__":
    main()
