#!/usr/bin/env python3
"""Stage 2a: the transition bracket, fully turbulent (SST, "tripped") against free transition
(kOmegaSSTLM), from the Stage 1 results. The difference is the most that tripping the boundary
layer can change in this model, at each alpha and speed.

    python3 cfd/stage2/compare_transition.py                          # Stage 1 CSV -> results/transition_bracket.*
    python3 cfd/stage2/compare_transition.py --csv <section_polars.csv> --out <dir>
    python3 cfd/stage2/compare_transition.py --stage2                 # also the texture pairs of Stage 2e

Input: cfd/section2d/results/section_polars.csv (written by the Stage 1 queue; read only). A pair is
two complete cases whose names differ only in the model token (_SST_ / _LM_), so level, Tu, run
length, time step and free stream match. With --stage2, pairs of texture cases
(cfd/stage2/results/stage2_polars.csv, wall tex, same t, seed, alpha, U) are added.

Output (in --out, default cfd/stage2/results/): transition_bracket.csv, transition_bracket.md and,
if matplotlib is available, transition_bracket.png. Per pair:
  dX = X_SST - X_LM for X = Cd, Cd_pressure, Cd_viscous, Cl, Cm, St;  dCd_pct = 100 dCd / Cd_LM.
  resolved: |dCd| > |Cd_drift_SST| + |Cd_drift_LM| (drift = mean of the second half of the
  averaging window minus the first half; a crude check of averaging error, not a confidence
  interval). 'no' means the difference is not resolved by this check; it does not show equality.
Prints a note and exits 0 if no pair exists yet (Stage 1 queue priority 2 makes them).
"""
import argparse
import csv
import math
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CFD = HERE.parent
STAGE1_CSV = CFD / "section2d" / "results" / "section_polars.csv"
STAGE2_CSV = HERE / "results" / "stage2_polars.csv"
QTY = ("Cd_mean", "Cd_pressure_mean", "Cd_viscous_mean", "Cl_mean", "Cm_mean", "St")


def fnum(v):
    try:
        x = float(v)
        return x if math.isfinite(x) else float("nan")
    except (TypeError, ValueError):
        return float("nan")


def read_csv(path):
    p = Path(path)
    if not p.exists():
        return []
    with open(p, newline="") as f:
        return list(csv.DictReader(f))


def pair_rows(rows, source):
    """[(SST row, LM row, source)] for names that differ only in the model token."""
    by = {r["name"]: r for r in rows}
    out = []
    for n, r in sorted(by.items()):
        if "_SST_" not in n:
            continue
        m = by.get(n.replace("_SST_", "_LM_", 1))
        if m is not None:
            out.append((r, m, source))
    return out


def bracket(pairs):
    res = []
    for s, l, src in pairs:
        d = dict(source=src, name_SST=s["name"], name_LM=l["name"], alpha_deg=fnum(s["alpha_deg"]),
                 U_ms=fnum(s["U_ms"]), Re_c=fnum(s.get("Re_c")), level=s.get("level", s.get("wall", "")),
                 Tu_pct=fnum(s.get("Tu_body_pct")), tex_t_mm=fnum(s.get("tex_t_mm", "nan")))
        for q in QTY:
            a, b = fnum(s.get(q)), fnum(l.get(q))
            k = q.replace("_mean", "")
            d[f"{k}_SST"], d[f"{k}_LM"], d[f"d{k}"] = a, b, a - b
        d["dCd_pct"] = 100 * d["dCd"] / d["Cd_LM"] if d["Cd_LM"] else float("nan")
        dr = abs(fnum(s.get("Cd_drift"))) + abs(fnum(l.get("Cd_drift")))
        d["Cd_drift_sum"] = dr
        d["resolved"] = "yes" if math.isfinite(dr) and abs(d["dCd"]) > dr else ("no" if math.isfinite(dr) else "n/a")
        res.append(d)
    res.sort(key=lambda d: (d["source"], d["level"], d["alpha_deg"], d["U_ms"]))
    return res


def write_outputs(res, out):
    out.mkdir(parents=True, exist_ok=True)
    cols = list(res[0].keys())
    with open(out / "transition_bracket.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for d in res:
            w.writerow({k: (f"{v:.6g}" if isinstance(v, float) else v) for k, v in d.items()})
    lines = ["# Transition bracket: SST (fully turbulent) minus LM (free transition)", "",
             "Generated by `cfd/stage2/compare_transition.py` from the complete Stage 1 cases"
             " (and Stage 2e texture pairs with `--stage2`). Calculated from the CSV rows; d = SST - LM.", "",
             "| Source | Mesh | alpha (deg) | U (m/s) | Cd SST | Cd LM | dCd | dCd (%) | dCd_p | dCd_v | dCl | dCm | St SST | St LM | resolved |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for d in res:
        mesh = d["level"] + (f" t {d['tex_t_mm']:.3f} mm" if d["source"] == "stage2" else "")
        lines.append(f"| {d['source']} | {mesh} | {d['alpha_deg']:g} | {d['U_ms']:g} | {d['Cd_SST']:.4f} | "
                     f"{d['Cd_LM']:.4f} | {d['dCd']:+.4f} | {d['dCd_pct']:+.1f} | {d['dCd_pressure']:+.4f} | "
                     f"{d['dCd_viscous']:+.4f} | {d['dCl']:+.4f} | {d['dCm']:+.4f} | {d['St_SST']:.3f} | "
                     f"{d['St_LM']:.3f} | {d['resolved']} |")
    lines += ["", "resolved: |dCd| larger than the sum of the two Cd drifts (second half of the averaging window"
              " minus the first half); 'no' bounds the difference, it does not show equality."]
    (out / "transition_bracket.md").write_text("\n".join(lines) + "\n")
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return
    s1 = [d for d in res if d["source"] == "stage1"]
    alphas = sorted({d["alpha_deg"] for d in s1})
    if not alphas:
        return
    fig, axs = plt.subplots(1, len(alphas), figsize=(5 * len(alphas), 4), squeeze=False)
    for ax, a in zip(axs[0], alphas):
        rr = sorted([d for d in s1 if d["alpha_deg"] == a], key=lambda d: d["U_ms"])
        for lev in sorted({d["level"] for d in rr}):
            q = [d for d in rr if d["level"] == lev]
            U = [d["U_ms"] for d in q]
            ax.plot(U, [d["Cd_SST"] for d in q], "o-", label=f"SST (tripped), {lev}")
            ax.plot(U, [d["Cd_LM"] for d in q], "s--", label=f"LM (free transition), {lev}")
        ax.set_xlabel("U (m/s)")
        ax.set_ylabel("Cd (c_ref 48 mm)")
        ax.set_title(f"alpha {a:g} deg")
        ax.grid(alpha=0.3)
        ax.legend(fontsize=8)
    fig.suptitle("Stage 2a transition bracket (Stage 1 cases)")
    fig.tight_layout()
    fig.savefig(out / "transition_bracket.png", dpi=130)
    plt.close(fig)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", default=str(STAGE1_CSV), help="Stage 1 polars CSV (default %(default)s)")
    ap.add_argument("--stage2", action="store_true", help="add SST/LM pairs of Stage 2e texture cases")
    ap.add_argument("--stage2-csv", default=str(STAGE2_CSV))
    ap.add_argument("--out", default=str(HERE / "results"))
    a = ap.parse_args()
    pairs = pair_rows(read_csv(a.csv), "stage1")
    if a.stage2:
        pairs += pair_rows([r for r in read_csv(a.stage2_csv) if r.get("wall") == "tex"], "stage2")
    if not pairs:
        print(f"no SST/LM pairs yet in {a.csv}" + (f" or {a.stage2_csv}" if a.stage2 else "")
              + " (Stage 1 queue priority 2 makes them); nothing written")
        return 0
    res = bracket(pairs)
    write_outputs(res, Path(a.out))
    for d in res:
        print(f"{d['source']:6s} {d['level']:6s} alpha {d['alpha_deg']:5.1f} U {d['U_ms']:4.1f}: Cd SST {d['Cd_SST']:.4f} "
              f"LM {d['Cd_LM']:.4f} dCd {d['dCd']:+.4f} ({d['dCd_pct']:+.1f} %), dCl {d['dCl']:+.4f}, "
              f"resolved {d['resolved']}")
    print(f"wrote {Path(a.out) / 'transition_bracket.csv'} (.md, .png)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
