#!/usr/bin/env python3
"""Stage 2b/2e: change of the section loads with roughness, against the smooth reference on the
same mesh, next to the transition bracket of Stage 2a.

    python3 cfd/stage2/compare_roughness.py            # results/stage2_polars.csv -> results/roughness_effects.*
    python3 cfd/stage2/compare_roughness.py --csv <stage2_polars.csv> --stage1-csv <section_polars.csv> --out <dir>

Groups (complete cases only; names starting with '_' are not in the CSV):
  wf   same alpha, U, Cs, KsEnds, Tu and run settings; reference Ks = 0 on the same wall-function mesh;
       d<X>(Ks) = X(Ks) - X(Ks = 0)
  tex  same alpha, U, model, seed, nseg, Tu; reference t = 0 (the texture mesh without
       displacement); d<X>(t) = X(t) - X(0)
Columns per case: Cd, dCd, dCd_pct, dCd_pressure, dCd_viscous, dCl, dCm, dSt, Ks+ (wf: estimated,
y+ Ks / y_P), resolved (|dCd| > sum of the two Cd drifts; 'no' does not show equality) and, where
Stage 1 has the SST/LM pair at the same alpha and U (medium, Tu 1 %), trip_dCd = Cd_SST - Cd_LM
(the Stage 2a bracket).
"""
import argparse
import csv
import math
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path[:] = [p for p in sys.path if Path(p or ".").resolve() != HERE]
sys.path.insert(0, str(HERE))
import compare_transition as ct  # noqa: E402

QTY = ("Cd_mean", "Cd_pressure_mean", "Cd_viscous_mean", "Cl_mean", "Cm_mean", "St")


def run_suffix(name):
    """Stage 1 run-setting suffixes (_Co, _N, _lt, _precomp) of a case name: part of the group key."""
    m = re.search(r"_Tu[\d.]+(.*)$", name)
    return m.group(1) if m else ""


def effects(rows, trip):
    out = []
    groups = {}
    for r in rows:
        w = r.get("wall")
        if w == "wf":
            key = ("wf", r["alpha_deg"], r["U_ms"], r["model"], r.get("Cs"), r.get("KsEnds_um"),
                   r.get("Tu_body_pct"), run_suffix(r["name"]))
            x = ct.fnum(r.get("Ks_um"))
        elif w == "tex":
            key = ("tex", r["alpha_deg"], r["U_ms"], r["model"], r.get("tex_seed"), r.get("Tu_body_pct"),
                   re.search(r"_s\d+(_n\d+)?", r["name"]).group(0), run_suffix(r["name"]))
            x = ct.fnum(r.get("tex_t_mm"))
        else:
            continue
        groups.setdefault(key, []).append((x, r))
    for key, items in sorted(groups.items()):
        items.sort(key=lambda q: q[0])
        ref = next((r for x, r in items if x == 0), None)
        for x, r in items:
            d = dict(wall=key[0], name=r["name"], alpha_deg=ct.fnum(r["alpha_deg"]), U_ms=ct.fnum(r["U_ms"]),
                     model=r["model"], rough=x, rough_unit="Ks um" if key[0] == "wf" else "t mm",
                     Cd=ct.fnum(r.get("Cd_mean")), ksplus_blade_mean=ct.fnum(r.get("ksplus_blade_mean")),
                     Ks_over_yP=ct.fnum(r.get("Ks_over_yP")), reference=ref["name"] if ref else "")
            for q in QTY:
                k = q.replace("_mean", "")
                d[f"d{k}"] = ct.fnum(r.get(q)) - ct.fnum(ref.get(q)) if ref else float("nan")
            d["dCd_pct"] = 100 * d["dCd"] / ct.fnum(ref.get("Cd_mean")) if ref else float("nan")
            dr = abs(ct.fnum(r.get("Cd_drift"))) + (abs(ct.fnum(ref.get("Cd_drift"))) if ref else float("nan"))
            d["resolved"] = ("n/a" if not math.isfinite(dr) or r is ref else ("yes" if abs(d["dCd"]) > dr else "no"))
            tb = trip.get((d["alpha_deg"], d["U_ms"]))
            d["trip_dCd"] = tb["dCd"] if tb else float("nan")
            d["trip_dCd_pct"] = tb["dCd_pct"] if tb else float("nan")
            out.append(d)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", default=str(ct.STAGE2_CSV))
    ap.add_argument("--stage1-csv", default=str(ct.STAGE1_CSV))
    ap.add_argument("--out", default=str(HERE / "results"))
    a = ap.parse_args()
    rows = ct.read_csv(a.csv)
    if not rows:
        print(f"no complete Stage 2 cases in {a.csv}; nothing written")
        return 0
    trip = {}
    for d in ct.bracket(ct.pair_rows(ct.read_csv(a.stage1_csv), "stage1")):
        if d["level"] == "medium" and abs(d["Tu_pct"] - 1.0) < 1e-6:
            trip[(d["alpha_deg"], d["U_ms"])] = d
    res = effects(rows, trip)
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    cols = list(res[0].keys())
    with open(out / "roughness_effects.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for d in res:
            w.writerow({k: (f"{v:.6g}" if isinstance(v, float) else v) for k, v in d.items()})
    lines = ["# Roughness effects against the smooth reference on the same mesh", "",
             "Generated by `cfd/stage2/compare_roughness.py` (calculated from `stage2_polars.csv`; d = rough - smooth;"
             " trip dCd = Stage 1 SST - LM, medium mesh, Tu 1 %).", "",
             "| Wall | alpha | U | Model | Ks (um) / t (mm) | Cd | dCd | dCd (%) | dCd_p | dCd_v | dCl | dSt | Ks+ (est.) | resolved | trip dCd |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for d in res:
        lines.append(f"| {d['wall']} | {d['alpha_deg']:g} | {d['U_ms']:g} | {d['model']} | {d['rough']:g} | {d['Cd']:.4f} | "
                     f"{d['dCd']:+.4f} | {d['dCd_pct']:+.1f} | {d['dCd_pressure']:+.4f} | {d['dCd_viscous']:+.4f} | "
                     f"{d['dCl']:+.4f} | {d['dSt']:+.3f} | {d['ksplus_blade_mean']:.3g} | {d['resolved']} | "
                     f"{d['trip_dCd']:+.4f} |")
    (out / "roughness_effects.md").write_text("\n".join(lines) + "\n")
    for ln in lines[4:]:
        print(ln)
    print(f"wrote {out / 'roughness_effects.csv'} (.md)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
